# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Kom1sh.MediaChef
PackageVersion: "0.7.0"
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Kom1sh/mediachef/releases/download/v0.7.0/MediaChef_0.7.0_x64-setup.exe
    InstallerSha256: F8D24BFEC0EC0BEA335C911F2E0B212E3E0985F9D3102037C7D7541EC2C2467D
ManifestType: installer
ManifestVersion: 1.12.0
